### PR TITLE
Update data type for bounding box coordinates to float32

### PR DESCRIPTION
**Pull request by hesamossanloo**
This pull request updates the data type for bounding box coordinates to float32. This change ensures compatibility with Apple M3 pro Chips #656

### CODE REVIEW

**Review by ethanwhite — CHANGES_REQUESTED** [review]
Nice work figuring this out @hesamossanloo!

My one thought is that there are a few additional uses of `.astype(float)` in `utilities.py` and I wonder if they should also be changed as part of this PR in case folks using M3's want to use those helper functions.

Whenever we're explicit we are using `float32` everywhere else, so the current changes  look good to me and I think making the same change in `utilities.py` makes sense.

That said I'll want @bw4sz to review and be the one to merge this one in case there is something subtle.

**Comment by henrykironde** [comment]
In the future, we should add test for MPS chips (Apple Silicon). Exploring current practices, it appears that many tests are conducted using purchased cloud or local instances.

**Review by bw4sz — APPROVED** [review]
This looks good to me, there is no downside to float versus float32 for just the annotations.

**Comment by bw4sz** [comment]
@ethanwhite did you request changes? I can see your review is blocking.

**Comment by ethanwhite** [comment]
> @ethanwhite did you request changes? I can see your review is blocking.

I was thinking about the additional uses of `.astype(float)` in `utilities.py` so we don't get caught by this again with the helper functions, but I'll approve this and open a new issue for those.

**Review by ethanwhite — APPROVED** [review]

**Comment by ethanwhite** [comment]
Thanks for the contribution @hesamossanloo! Since @bw4sz has approved this as well I'm merging.

**Comment by hesamossanloo** [comment]
Cheers @ethanwhite, @bw4sz :) I should thank you for keeping this great project running.

**Pull request merged**
