### PR TITLE
Training model on OSBS Dataset

### PR DESCRIPTION
**Pull request by dassaniansh**

### CODE REVIEW

**Comment by ethanwhite** [comment]
Looks like we've got duplicates of the image files in a `_MACOSX` subdirectory. Let's remove those.

**Comment by dassaniansh** [comment]
Thanks for it @ethanwhite, Sorry I didn't notice that I pushed those files too.

**Comment by ethanwhite** [comment]
No problem - that's why we do reviews!

**Review by ethanwhite — APPROVED** [review]

**Comment by ethanwhite** [comment]
@henrykironde & @bw4sz I think this PR got lost in the fall. My review was just on a detail since I wasn't involved in the project. Is this something we want to get merged in?

**Comment by bw4sz** [comment]
No, this is not the location for these experiments. As part of milestone 2.0, we need some organization for where DeepForest research goes.

**Pull request closed without merging**
