### PR TITLE
add on epoch end val metric

### PR DESCRIPTION
**Pull request by bw4sz**
@ethanwhite I'm testing this now. It will come with some reduction in the speed of training due to matching with the boxes. i've added a config arg to control how often accuracy is checked.

### CODE REVIEW

**Comment by bw4sz** [comment]
closes https://github.com/weecology/DeepForest/issues/273

**Comment by ethanwhite** [comment]
:+1: Happy to have some slowdown to get this info during training and I think the config arg is a great way to let the user handle the tradeoffs

**Comment by bw4sz** [comment]
DeepForest experiment (just one class, so recall and precision are always 1) is here

https://www.comet.ml/bw4sz/deepforest-pytorch/fa8f8297cff741d2bdbeffe6af89ec69?experiment-tab=metrics&viewId=RhhMXsRA1UdsXTxZv13D7WJ8e
Screen Shot 2021-12-13 at 1 59 07 PM

it runs, but i'm unhappy about the worker slowdown. and it needs better labels?

**Comment by bw4sz** [comment]
I'm going to merge this and open a new branch on profiling.

**Pull request merged**
