### PR TITLE
Added gradio app for getting started tutorial

### PR DESCRIPTION
**Pull request by Om-Doiphode**
Fixes issue #634 

I have created a folder named `gradio_app` which contains the file `app.py` for the gradio application. I have included the Getting Started tutorial for the Bird and Tree Models. Following are the screenshots of the application:

image
image
image

### CODE REVIEW

**Comment by bw4sz** [comment]
Great, let's make that doc read.

```
# Demo

[Try out the DeepForest models online!](<link>)
```
then I think i'm ready to merge.

**Comment by bw4sz** [comment]
Just that last edit and i'll bypass the errors from #636

**Comment by Om-Doiphode** [comment]
> Great, let's make that doc read.
> 
> ```
> # Demo
> 
> [Try out the DeepForest models online!](<link>)
> ```
> 
> then I think i'm ready to merge.

I have done the change, please review it. Thanks!

**Comment by bw4sz** [comment]
@ethanwhite ```Hugging Face provides the basic computing resources for running the demo app, including 16 GB of RAM, 2 CPU cores, and 50 GB of disk space for free.```

I'm happy to merge. Thanks @Om-Doiphode

**Pull request merged**
