### PR TITLE
Fixed deprecation warning

### PR DESCRIPTION
**Pull request by Om-Doiphode**
solved issue #369.

### CODE REVIEW

**Comment by Om-Doiphode** [comment]
Solved issue #369

**Comment by Om-Doiphode** [comment]
Hello @ethanwhite, can you please suggest any changes to improve the code since the Conda Cl setup is failing everytime.

**Comment by ethanwhite** [comment]
The changes look fine. @henrykironde is currently working on finding out what the tests aren't running properly.

@labeeb-7z Also proposed a solution to this in https://github.com/weecology/DeepForest/pull/374. The specific value for weights the two of you selected was slightly different. Are the two selections equivalent and if not which one is exactly the same as the old `pretrained=True`?

**Comment by Om-Doiphode** [comment]
@ethanwhite, According to the following warning which was encountered previously:

``UserWarning:Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=RetinaNet_ResNet50_FPN_Weights.COCO_V1`. You can also use `weights=RetinaNet_ResNet50_FPN_Weights.DEFAULT` to get the most up-to-date weights.``

According to the above warning, COCO_V1 is equivalent to pretrained=True.

**Comment by ethanwhite** [comment]
Thanks @Om-Doiphode - and what is the difference between that and the usage in #374 - or do they use the same pretraining with different names?

**Comment by Om-Doiphode** [comment]
@ethanwhite According to the [docs](https://pytorch.org/vision/master/models/generated/torchvision.models.detection.retinanet_resnet50_fpn.html#torchvision.models.detection.RetinaNet_ResNet50_FPN_Weights), both are equivalent.
image

**Review by ethanwhite — APPROVED** [review]
LGTM @Om-Doiphode! I'm rerunning the tests now that @henrykironde's fix is in and once everything is passing I'll get this merged.

**Comment by henrykironde** [comment]
@Om-Doiphode update your branch

**Comment by Om-Doiphode** [comment]
@ethanwhite Can you please tell me on what to do further to improve the code since one test case is failing.
image

I think 'm' is either getting deleted or it's present in a scope which is inaccessible.

**Comment by henrykironde** [comment]
@Om-Doiphode I will have a look and get back to you

**Comment by henrykironde** [comment]
@Om-Doiphode squash the commits, and make sure the branch is up to date with the main.

**Comment by ethanwhite** [comment]
@henrykironde - I suggest we go ahead and merge this one since it's not causing the test failures.

**Comment by ethanwhite** [comment]
It's been 2 weeks so I'm going to go ahead and merge this.

**Comment by ethanwhite** [comment]
Thanks for your contribution @Om-Doiphode!

**Pull request merged**
