### PR TITLE
[WIP] Examples dir

### PR DESCRIPTION
**Pull request by bw4sz**
Start to create ipython examples.

### CODE REVIEW

**Comment by bw4sz** [comment]
@henrykironde this builds, but i'm not sure how it will render on readthedocs.

**Review by henrykironde — COMMENTED** [review]
The documentation undergoes testing for each pull request. You can view the rendered pages in the test details: `docs/readthedocs.org:deepforest — Read the Docs build succeeded!` 

let's improve its usability. 
- Remove personal hard coded paths
    We can store sample images on Zenodo and download them during notebook setup.       Ensure paths are relative to the downloaded files.  

- Can we add test?

  We do have a sample notebook test, `docs/sample.ipynb`. 
  If notebook runtime is short, we can include it in GitHub actions tests; otherwise, we can create a cronjob for local testing.

**Comment by bw4sz** [comment]
Runtimes are not short, can we cache certain blocks? For these walkthroughs its probably imnportant we show the full workflow. Its like 25min on a decent CPU. I logged into readthedocs and I can see the build and then I viewed from there. That works. I want to nest it inside of /examples

image

**Comment by bw4sz** [comment]
- [ ] Nest notebooks in an 'examples' tab on readthedocs.
- [ ] Clean up final figure.
- [ ] Record a loom walkthrough
- [ ] The first tab doesn't have the code for prediction, but the text does. 
- [ ] The blue color is hard to see on the readthedocs theme, make it orange or black.

**Comment by bw4sz** [comment]
Sorry, I messed up the rebase. Closing and reopening. https://github.com/weecology/DeepForest/pull/689

**Pull request closed without merging**
