### PR TITLE
Bug fix plot predictions

### PR DESCRIPTION
**Pull request by bw4sz**
This is a small pull request. The plot_predictions_dataframe function had an optional savedir arg, but if you didn't specify a savedir, the function didn't actually return anything. savedir cannot be optional.

### CODE REVIEW

**Comment by ethanwhite** [comment]
`test_IoU::test_compute_IoU` needs to be updated to match

**Comment by bw4sz** [comment]
Fixed in 6ec71a29f1a8f8d8394a9f6c1de20d02c28cfb43

**Comment by ethanwhite** [comment]
New test failures that aren't part of other issues (that I'm aware of)

**Comment by bw4sz** [comment]
also the git history is weird here too, not sure how this crept in.

**Comment by ethanwhite** [comment]
We've fixed the external test issues so this just needs the history cleaned up to only reflect the relevant changes and then it should be ready to go in.

**Comment by bw4sz** [comment]
@ethanwhite I have cleaned the history to reflect just the appropriate commits.

**Review by ethanwhite — CHANGES_REQUESTED** [review]
Looks good. The docs failure is clearly independent. The Azure failure is likely code style due to a couple of long lines. You can either fix them manually or do

```
yapf -i --recursive deepforest/ --style=.style.yapf
```

Once the style check is happy this is ready to merge.

**Comment by bw4sz** [comment]
Pushed style changes (after accidentally running it on main)

**Comment by ethanwhite** [comment]
So now it looks like we have a duplicate commit of https://github.com/weecology/DeepForest/commit/78920b4f19545b88ae7a4f20edb7290f7a343227 which is now in `main`? Given the duplicate commit I think we should probably rebase. If you're still working I can walk you through it.

I'm also still trying to figure out how you pushed to `main` with branch protection on.

**Comment by bw4sz** [comment]
Closing in favor of a new PR, not sure how this branch got all messed up.

**Pull request closed without merging**
