### PR TITLE
Add precommit file

### PR DESCRIPTION
**Pull request by Mu-Magdy**
Added config file to use style yapf style 

Tested it locally and it prevented to commit bad formatted code.

### CODE REVIEW

**Comment by Mu-Magdy** [comment]
Hi @henrykironde, I tried to use yabf module in a .py file but i found this way to be easier. I can try the other way if you recommend it

**Comment by Mu-Magdy** [comment]
closes #711

**Comment by henrykironde** [comment]
@Mu-Magdy, thank you for your work on this. Could you please add some developer documentation about pre-commit? I'm attempting to run it locally but am not able to.

**Review by henrykironde — CHANGES_REQUESTED** [review]
Update PR

**Review by ethanwhite — CHANGES_REQUESTED** [review]
@Mu-Magdy I'm going to leave @henrykironde to handle the content review, but looking at the history we have 7 commits for for what amounts to a single change. Can you please rebase this into a single commit with a good descriptive commit message.

**Review by henrykironde — APPROVED** [review]
I will squash the  commits. LGTM

**Pull request closed without merging**
