### PR TITLE
Remove soft-nms from the project

### LINKED ISSUE #471: Get rid of soft-nms
I have never seen it used and it just adds clutter to the decision making process.

### PR DESCRIPTION
**Pull request by satsin06**
Fix #471

### CODE REVIEW

**Comment by bw4sz** [comment]
Thanks for this PR. Can you run

```
yapf -d --recursive deepforest/
```

so the style checks pass.

**Review by bw4sz — COMMENTED** [review]
Thanks for this PR.

**Comment by satsin06** [comment]
> Thanks for this PR. Can you run
> 
> ```
> yapf -d --recursive deepforest/
> ```
> 
> so the style checks pass.

Hi, I just add an another commit which fixes the style check. Thank you

**Comment by ethanwhite** [comment]
Everything is passing now

**Review by bw4sz — APPROVED** [review]

**Pull request merged**
