### PR TITLE
Issue 516 boxes to shapefile should take in absolute path to rgb

### PR DESCRIPTION
**Pull request by 2ArounD**
Hi!

The DeepForest project sounds awesome, so I'm looking to contribute. To get started I picked up one of the issues and fixed it. Let me know what you think. I hope to learn more about this project while contributing!

All the best,
Arnoud

### CODE REVIEW

**Comment by bw4sz** [comment]
Awesome. We love new contributors. What's your background and interest? You picked an interesting issue. My first reaction was, was that really labeled good first issue? I think there are some downstream effects that need to be thought about here that I will review tomorrow. I think there are several functions that assume relative paths. This is definitely needed and important, since its quite strange that DeepForest API insists the file structure has a certain setup, its clearly a design flaw related to the history of the project. Something we want to improve. I'll take a detailed look tomorrow.

**Comment by 2ArounD** [comment]
My background in a nutshell:
Education: MsC in mechanical engineering, with lot's of focus on software, computer vision and AI for self driving 
Work experience: Data scientist/software engineer. 
Previously: 2 years in a company focused on document automation (lot's of optical character recognition and text classification).
Current: 1 year in a company focused on Bird monitoring with video cameras (lot's of computer vision and machine learning)
I am based in Oslo

Interests: Going to the mountains and the forest, picking mushrooms, picking berries, cross country skiing, ice skating, kayaking, cycling, rugby, cooking, AI, ecology, sustainable energy 

When I woke up this morning I realised I didn't look through the repository for usage of the function, only triggered the tests, good idea to check that. Just ping me on what needs to happen.

**Comment by bw4sz** [comment]
Great, its thanksgiving break here, so a short delay in reviewing this.

**Comment by 2ArounD** [comment]
No problem! Review it when you have time

**Review by bw4sz — CHANGES_REQUESTED** [review]
See conversation, let's move original behavior to if statement and raise DeprecationWarning.

**Comment by bw4sz** [comment]
Great. I'm now remember why this had a good_first_issue tag. We are leaving the wider question of absolute path versus relative path, which underlies a half dozen training functions, like https://deepforest.readthedocs.io/en/latest/training.html and just concerns itself with this one function. Let's do two things. We don't like breaking changes if we don't need them. We want to adopt a strategy of warn users and then set a deprecation time. 

1. Keep the root_dir argument. 
2. If root_dir is specified, raise DeprecationWarning and tell user that relative path will be deprecated in DeepForest 2.0 and please specify absolute path. 
3. Then have an if statement.

https://github.com/weecology/DeepForest/blob/af1c4d4a76064c1834f0cbdf2986a978204593e4/deepforest/utilities.py#L398

```
if root_dir:
   rgb_path = "{}/{}".format(root_dir, plot_name)
```

4. Minor detail, elsewhere we use image_path, not rgb_image_path, shorter naming of the arg and matching with other functions.

Thanks for your PR, we appreciate all the help as we grow the community.

**Comment by ethanwhite** [comment]
Closing due to inactivity. Feel free to reopen if anyone comes back to this.

**Pull request closed without merging**
