### PR TITLE
Use models from Huggingface

### PR DESCRIPTION
**Pull request by henrykironde**

### CODE REVIEW

**Comment by henrykironde** [comment]
@ethanwhite and @bw4sz, I know there are a lot of changes here, but the HuggingFace platform updates are only in the first commit. I’ve also submitted a separate PR (#747) for improved visualization of those changes. The tests folder changes in this PR are just style cleanups.

**Comment by ethanwhite** [comment]
Thanks @henrykironde. I've read the PR and tested locally. Works great! Still thinking through a couple of things, but hoping to get a review up for you today.

**Comment by henrykironde** [comment]
Once this is merged, we shall change the main.use_release() and main.use_bird_release() functions, add a deprecated message.

**Review by ethanwhite — APPROVED** [review]
LGTM!

**Pull request merged**
