### PR TITLE
Release version update

### PR DESCRIPTION
**Pull request by henrykironde**

### CODE REVIEW

**Review by ethanwhite — APPROVED** [review]
LGTM

**Comment by henrykironde** [comment]
@ethanwhite do you think we should amend/squash the second commit or leave it in the history?

**Comment by ethanwhite** [comment]
> @ethanwhite do you think we should amend/squash the second commit or leave it in the history?

No strong feelings. It's a weird situation. Whatever you think is best is good by me

**Comment by henrykironde** [comment]
@ethanwhite with the current structure we have 
```Python
>>> from deepforest._version import __version__
>>> __version__
'1.4.1'

```

**Comment by ethanwhite** [comment]
Is that a new Python standard?

**Comment by ethanwhite** [comment]
I'm booked most of the afternoon so @henrykironde just go with what you think is best. My thinking was based on `deepforest.__version__` being a de facto standard:

https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package

But if that has changed I'm fine with doing it differently. I'm going to change to Approve so that I'm not blocking you and @bw4sz finishing off the release

**Review by ethanwhite — APPROVED** [review]

**Pull request merged**
