### PR TITLE
Update package to address deprecation warnings #625- Preview Me

### PR DESCRIPTION
**Pull request by ire-mide1**
Address the deprecation warning regarding the use of return instead of assert in the test test_retinanet within tests/test_FasterRCNN.py

### CODE REVIEW

**Comment by henrykironde** [comment]
@ire-mide1 avoid using the main branch. Try to use a new branch for each issue or problem being solved.

**Comment by ire-mide1** [comment]
Noted

**Comment by ethanwhite** [comment]
@ire-mide1 - I'm guessing that you didn't mean to include the file `deepforest/models/# Model.py` in this PR. Can you remove it and update the PR?

Depending on your level of git experience it may be easiest to save your changes to `tests/test_FasterRCNN.py` outside of the repository, create a new branch from `main`, and then copy the saved file with your changes back into the repo. Once that's done we can give this will hopefully fix the failing tests and then we can take a look at the PR. Let me know if you have any questions as you go.

**Comment by ethanwhite** [comment]
Closing due to inactive. Feel free to reopen if you return to this.

**Pull request closed without merging**
