### PR TITLE
Add functionality for split raster to read in from pandas

### PR DESCRIPTION
**Pull request by bw4sz**
The prior behavior before geo_type branch was merged was to allow pandas dataframes to go directly into preprocess.split_raster, its easy to keep continuity with this behavior by wrapping any pandas dataframes into utilities.read_file to get the geometry column needed. The user shouldn't have to do this. Test confirms functionality.

### CODE REVIEW

**Review by ethanwhite — APPROVED** [review]
LGTM

**Comment by ethanwhite** [comment]
Tests still failing. I think the `.tif` extension in the original commit was correct (at least that's what's in `OSBS_029.csv`)

**Comment by bw4sz** [comment]
strange, I just changed it back and it worked.

**Comment by bw4sz** [comment]
This PR achieves three things

- Allows as a pandas dataframe to be passed to split_raster, maintaining previous behavior.
- Yields annotation files that are match training expectations for negative samples when allow_empty is True (updated from when https://github.com/weecology/DeepForest/pull/721/files was merged)
- Updates a geometry column with cropped annotations after cropping for points, boxes, polygons.

@ethanwhite its hard to know how robust the empty frames pathway was, it might be interested once this is merged to install and fire off a round to see if it mattered for formatting.

**Comment by ethanwhite** [comment]
Looks like a style fix needed now

**Comment by bw4sz** [comment]
> Looks like a style fix needed now

I thought we had a pre-commit hook for this now? #712

**Comment by bw4sz** [comment]
I squashed to improve git logs

**Comment by ethanwhite** [comment]
> I thought we had a pre-commit hook for this now? https://github.com/weecology/DeepForest/pull/712

We do. Did you [set it up to run locally](https://github.com/weecology/DeepForest/blob/main/CONTRIBUTING.md#using-pre-commit)?

**Review by ethanwhite — APPROVED** [review]
Looks good!

**Pull request merged**
