### PR TITLE
Update README.md in response to Sample Image Issue numbered 49

### PR DESCRIPTION
**Pull request by malayjoshi13**
This commit is in response to "Sample Image Issue #49" posted in the "weecology/DeepForest" repository's Issues section.

This image will let the user get a better practical real-time use-case of this python package. It will do so as this image has a combination of both trees (that too of different variations in height and crown size) and non-tree objects (to be specific vehicles, buildings and concrete flooring ). However, still from the image attached, it is very well clear that the python package has very accurately recognized only trees and marked them with bounding boxes.

Thus, in short, this committed image will encourage more users to trust, get more comfortable using this python package in their projects and contributing in return towards the development of the DeepForest package.

### CODE REVIEW

**Comment by malayjoshi13** [comment]
Hi,
Since yesterday I am trying to open a pull request to propose a change in README.md to issue number 49. I tried multiple ways, but all in vain. Can you please tell me where I am making a mistake so that I can create a PR easily in the future?

**Comment by bw4sz** [comment]
Thats fine, but can you not delete the current one and just add the second? Those issues in the git tests are known, @henrykironde , its something to do with the SSL certificate of the wheel builder. Low priority, but keeping tests from running on windows.

**Comment by malayjoshi13** [comment]
Can you please elaborate what are you exactly expecting me to do? I have not got your reference of first and second.

**Comment by malayjoshi13** [comment]
I mean I have already closed all previous PRs. Right now only most latest one is active as I am debugging how to pass the remaining two checks. So please tell what exactly are you expecting me to close and which one to remain open?

**Comment by ethanwhite** [comment]
I think there me some miscommunication happening here so I'm going to try to help clear it up. If I'm understanding correctly I think that @malayjoshi13 has basically been trying to submit just the change in this PR, but running into issues with the failing tests.

@malayjoshi13 - what is saying in https://github.com/weecology/DeepForest/pull/176#issuecomment-812141382 is that the failing tests are not related to your PR, they are an issue with our build system that we're still trying to get sorted out. So, you submitted your PR correctly and everything is working as expected.

Assuming I'm understanding all of this correctly @bw4sz can go ahead and merge this PR and everything should be good.

**Comment by malayjoshi13** [comment]
Hi, @bw4sz are the azure pipelines now been corrected? Should I now re-try to pass these checks by opening a new pull request with the current commit or its possible for you to merge the existing PR itself ?

**Comment by henrykironde** [comment]
@malayjoshi13 You can create a new PR.

It is recommended that you do not use master. Always create a new branch from master
A few setup to follow.

Check your config file remotes(you will notice the difference after the next step)
`git remote -v`

Add upstream(make git know that the origin copy of the repo comes from `weecology/DeepForest`, and call it upstream)
`git remote add upstream https://github.com/weecology/DeepForest.git`

Check your config file again to see if **upstream** is present
`git remote -v`

Before you create a new branch, update your local copy of the repo (master)
`git fetch upstream master`

Force the local copy of master to be the same as the upstream master

`git reset --hard upstream/master`

Now you can create a new branch. For example `git checkout -b sample-image-issue`

At this point you can `add` all your changes, `commit`, `push` and create a new PR

`git add -u`

**Either :**
`git commit -m"Update README.md in response to Sample Image Issue numbered  #49"`
or 
```
git commit -m"Use a new Sample Image

Fixes #49"
```
**Push**
`git push origin sample-image-issue`

**Comment by malayjoshi13** [comment]
Thank you @bw4sz, @henrykironde and @ethanwhite for guiding. I have opened a new PR and it has passed all the checks so I am closing this one.

**Pull request closed without merging**
