### PR TITLE
Updated environment.yml file

### PR DESCRIPTION
**Pull request by Om-Doiphode**
Fixes issue #543

### CODE REVIEW

**Review by ethanwhite — APPROVED** [review]
LGTM. Assuming the Azure tests pass I think that this is ready for either @bw4sz or @henrykironde to merge.

**Comment by ethanwhite** [comment]
Looks like Azure just had a hiccup in the initial run. I've rerun, everything is passing, and this looks good to me so I'm going to go ahead and get it merged.

**Comment by ethanwhite** [comment]
@Om-Doiphode One note for future PRs is to be a little more explicit with your commit messages. E.g., in this case a good one-line commit message would have been something like:

```
Install pytorch and torchvision from the pytorch conda channel
```

You can also link PR's directly to the issues they are addressing by doing something like:

```
Install pytorch and torchvision from the pytorch conda channel

Fixes #543 
```

And here's the full commit message that I would have written:

```
Install pytorch and torchvision from the pytorch conda channel

This provides proper support for GPU's when install via conda.

Fixes #543 
```

**Comment by Om-Doiphode** [comment]
Ok @ethanwhite, I will take care of this in my future Pull requests. Thank you!

**Pull request merged**
