### PR TITLE
Update to new pytorch-lightning API

### PR DESCRIPTION
**Pull request by ethanwhite**
The new API no longer provides a number of gpus of separately, it is now
provided in the generic `devices` argument and `gpu` is set in `accelerator`.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Assuming most of our tests start passing again this is a priority to get reviewed (and it should be checked carefully) and merged since I think all new installs or installs that update pytorch-lightening will be broken.

**Comment by ethanwhite** [comment]
Note that this fixes the 76 tests failures resulting from using `gpus` but one test is still failing, which is `test_train_no_validation`:

https://github.com/weecology/DeepForest/blob/8e91b0ae8c6296cc9d62dd229335b04fd29ca7c9/tests/test_main.py#L117-L121

Resulting error:

```
(DeepForest) ethan@pop-os:~/Dropbox/Informatics/DeepForest$ pytest -v -k test_train_no_validation
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.10.9, pytest-7.2.2, pluggy-1.0.0 -- /home/ethan/miniconda3/envs/DeepForest/bin/python3.10
cachedir: .pytest_cache
rootdir: /home/ethan/Dropbox/Informatics/DeepForest, configfile: setup.cfg
collected 77 items / 76 deselected / 1 selected                                                                                                                           

tests/test_main.py::test_train_no_validation FAILED                                                                                                                 [100%]

================================================================================ FAILURES =================================================================================
________________________________________________________________________ test_train_no_validation _________________________________________________________________________

dataloader = None
source = _DataLoaderSource(instance=deepforest(
  (model): RetinaNet(
    (backbone): BackboneWithFPN(
      (body): Intermedia...229, 0.224, 0.225])
        Resize(min_size=(800,), max_size=1333, mode='bilinear')
    )
  )
), name='val_dataloader')
trainer_fn = <TrainerFn.FITTING: 'fit'>

    def _check_dataloader_iterable(
        dataloader: object,
        source: _DataLoaderSource,
        trainer_fn: TrainerFn,
    ) -> None:
        try:
>           iter(dataloader)  # type: ignore[call-overload]
E           TypeError: 'NoneType' object is not iterable

../../../miniconda3/envs/DeepForest/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:383: TypeError

During handling of the above exception, another exception occurred:

m = deepforest(
  (model): RetinaNet(
    (backbone): BackboneWithFPN(
      (body): IntermediateLayerGetter(
        (con..., 0.456, 0.406], std=[0.229, 0.224, 0.225])
        Resize(min_size=(800,), max_size=1333, mode='bilinear')
    )
  )
)

    def test_train_no_validation(m):
        m.config["validation"]["csv_file"] = None
        m.config["validation"]["root_dir"] = None
        m.create_trainer()
>       m.trainer.fit(m)

tests/test_main.py:121: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../miniconda3/envs/DeepForest/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:520: in fit
    call._call_and_handle_interrupt(
../../../miniconda3/envs/DeepForest/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py:44: in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
../../../miniconda3/envs/DeepForest/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:559: in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
../../../miniconda3/envs/DeepForest/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:935: in _run
    results = self._run_stage()
../../../miniconda3/envs/DeepForest/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:978: in _run_stage
    self.fit_loop.run()
../../../miniconda3/envs/DeepForest/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py:197: in run
    self.on_run_start()
../../../miniconda3/envs/DeepForest/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py:308: in on_run_start
    self.epoch_loop.val_loop.setup_data()
../../../miniconda3/envs/DeepForest/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py:168: in setup_data
    _check_dataloader_iterable(dl, source, trainer_fn)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

dataloader = None
source = _DataLoaderSource(instance=deepforest(
  (model): RetinaNet(
    (backbone): BackboneWithFPN(
      (body): Intermedia...229, 0.224, 0.225])
        Resize(min_size=(800,), max_size=1333, mode='bilinear')
    )
  )
), name='val_dataloader')
trainer_fn = <TrainerFn.FITTING: 'fit'>

    def _check_dataloader_iterable(
        dataloader: object,
        source: _DataLoaderSource,
        trainer_fn: TrainerFn,
    ) -> None:
        try:
            iter(dataloader)  # type: ignore[call-overload]
        except TypeError:
            # A prefix in the message to disambiguate between the train- and (optional) val dataloader that .fit() accepts
            prefix = "train_" if trainer_fn == TrainerFn.FITTING else ""
            if not source.is_module():
                raise TypeError(
                    f"An invalid dataloader was passed to `Trainer.{trainer_fn}({prefix}dataloaders=...)`."
                    f" Found {dataloader}."
                )
            if not is_overridden(source.name, source.instance):
                raise TypeError(
                    f"An invalid dataloader was passed to `Trainer.{trainer_fn}({prefix}dataloaders=...)`."
                    f" Found {dataloader}."
                    f" Either pass the dataloader to the `.{trainer_fn}()` method OR implement"
                    f" `def {source.name}(self):` in your LightningModule/LightningDataModule."
                )
>           raise TypeError(
                f"An invalid dataloader was returned from `{type(source.instance).__name__}.{source.name}()`."
                f" Found {dataloader}."
            )
E           TypeError: An invalid dataloader was returned from `deepforest.val_dataloader()`. Found None.

../../../miniconda3/envs/DeepForest/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:399: TypeError
```

Not sure if this is a change in lightening or something else, but it shouldn't effect general usage.

**Comment by bw4sz** [comment]
This is caused by the fast dev run overriding the trainer args. This isn't well documented. I made an issue. Reproducible.

```
import os

import torch
from torch.utils.data import DataLoader, Dataset
from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning import __version__

class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self, run_validate):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
        self.run_validate = run_validate

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def val_dataloader(self):
        if self.run_validate:
            dataloader = DataLoader(RandomDataset(32, 64), batch_size=2)        
        return dataloader
    
    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run(fast_dev_run):
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel(run_validate=True)
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=0,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
        fast_dev_run=fast_dev_run
    )
    trainer.fit(model, train_dataloaders=train_data)


if __name__ == "__main__":
    print(__version__) 
    
    #Works as expected, no validation
    run(fast_dev_run=False)
        
    #Runs validation even though trainer sas no steps
    run(fast_dev_run=True)
```

The solution is to just run 1 batch of training for the test

```
def test_train_no_validation(m):
    m.config["train"]["fast_dev_run"] = False    
    m.config["validation"]["csv_file"] = None
    m.config["validation"]["root_dir"] = None  
    m.create_trainer(limit_train_batches=1)
    m.trainer.fit(m)
 ```

and add a if statement when creating the trainer

```

    def create_trainer(self, logger=None, callbacks=[], **kwargs):
        """Create a pytorch lightning training by reading config files
        Args:
            callbacks (list): a list of pytorch-lightning callback classes
        """

        # If val data is passed, monitor learning rate and setup classification metrics
        if not self.config["validation"]["csv_file"] is None:
            if logger is not None:
                lr_monitor = LearningRateMonitor(logging_interval='epoch')
                callbacks.append(lr_monitor)
            limit_val_batches = 1.0
            num_sanity_val_steps = 2
        else:
            # Disable validation, don't use trainer defaults
            print("Turning off validation loop")            
            limit_val_batches = 0
            num_sanity_val_steps = 0
        # Check for model checkpoint object
        checkpoint_types = [type(x).__qualname__ for x in callbacks]
        if 'ModelCheckpoint' in checkpoint_types:
            enable_checkpointing = True
        else:
            enable_checkpointing = False
        
        self.trainer = pl.Trainer(logger=logger,
                                  max_epochs=self.config["train"]["epochs"],
                                  enable_checkpointing=enable_checkpointing,
                                  devices=self.config["devices"],
                                  accelerator=self.config["accelerator"],
                                  fast_dev_run=self.config["train"]["fast_dev_run"],
                                  callbacks=callbacks,
                                  limit_val_batches=limit_val_batches,
                                  num_sanity_val_steps=num_sanity_val_steps,
                                  **kwargs)
```
I will edit this PR to reflect these changes.

**Comment by bw4sz** [comment]
This was a nice chance for me to interact with pytorch lightning issue queue. We could learn alot from how they setup their issues. https://github.com/Lightning-AI/lightning/issues/17154

**Comment by bw4sz** [comment]
I don't follow, all tests are now passing,  but there is a vague error.

https://dev.azure.com/benweinstein2010/DeepForest/_build/results?buildId=433&view=ms.vss-test-web.build-test-results-tab

memory error?

https://dev.azure.com/benweinstein2010/DeepForest/_build/results?buildId=433&view=logs&j=8a08b103-7f3c-5f4b-1889-6a795acbb007&t=1cd20482-70c8-5631-9c42-a1b31638d943&l=2065

**Review by bw4sz — COMMENTED** [review]
This looks good to me. Thanks for looking into this.

**Comment by ethanwhite** [comment]
All passing locally for me as well

**Comment by bw4sz** [comment]
Probably unrelated to our error, but pytorch maintainers say that the preferred solution is 

https://github.com/Lightning-AI/lightning/issues/17154

```
return []

instead of return None
```
for an empty iterator. We can add tomorrow, but tests are already passing, so that's not what is going on here.

**Comment by ethanwhite** [comment]
So do you just want me to change

https://github.com/weecology/DeepForest/blob/8e91b0ae8c6296cc9d62dd229335b04fd29ca7c9/deepforest/main.py#L218

to

```python
loader = []
```

 or switch to the more general structure of the conditional in that issue?

**Comment by bw4sz** [comment]
@henrykironde can you approve this review and merge. Then open a new issue documenting the azure pipeline errors. All tests pass, I think this PR is important enough to get to main and then we need to get azure pipelines to pass so we can get it on pypi. I think these issues are separate.

**Comment by ethanwhite** [comment]
I think @henrykironde is in the field this week so given the importance and the fact that we've both looked at each others code I'll go ahead and get this merged.

**Pull request merged**
