### PR TITLE
Ask user if they want to download the latest model. #321 with test cases passed 

### PR DESCRIPTION
**Pull request by ayeankit**
Implementation for '`check_new_release' `method and write up code for the user permission if they want to download the latest model . And added test cases of new function in test folder. and clean up the code according to google chromium style. I have created test cases and passed.

### CODE REVIEW

**Comment by ayeankit** [comment]
hey @henrykironde , I don't know why this is failing, Locally all the test cases are passed, as you can see.
Screenshot from 2023-03-10 17-29-55

Please suggest some solution for passing this.

**Comment by henrykironde** [comment]
Can you run these two commands and let me know what the results are?

```
git clean -fxd
pytest -v -k"release"
```

**Comment by ayeankit** [comment]
Hey @henrykironde , Here are results after executing the above command.

Screenshot from 2023-03-12 00-07-43
Screenshot from 2023-03-12 00-08-02
Screenshot from 2023-03-12 00-08-14

**Comment by henrykironde** [comment]
So locally it does not pass the testing, Try to debug that, find out why there is a file missing.

**Pull request closed without merging**
