### PR TITLE
Fixed error related to tile assignment

### PR DESCRIPTION
**Pull request by Om-Doiphode**
Fixes issue #427

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks for this fix @Om-Doiphode! Do you have time to add a test associated with the change to avoid a regression in the future?

**Comment by Om-Doiphode** [comment]
Hi @ethanwhite, can you guide me on how to write a test for this change? Because I have looked at the `deepforest/tests/test_main.py` file and I can't understand on how to write a test for the current issue. Like how the `tile` variable can be accessible in another file (`deepforest/tests/test_main.py` file). Should I write some assert condition within the `predict_tile` function in the `deepforest/main.py`?

**Comment by ethanwhite** [comment]
I think we basically just need a copy of the current `test_predict_tile_from_array` function:

https://github.com/weecology/DeepForest/blob/54288a62753de4df0919884b3c40eb88258a9aca/tests/test_main.py#L248-L257

But with `return_plot = TRUE`. We need to change the assert statement a little since we're getting back a numpy ndarray. We could use `isinstance(prediction, np.ndarray)` to check the type of the returned value or check its size to make sure it's not empty `np.size(prediction) > 0`.

Does that help?

**Comment by Om-Doiphode** [comment]
HI @ethanwhite, Thanks for the explanation! I have made the necessary changes. Please review, thanks!

**Review by ethanwhite — APPROVED** [review]
Looks great @Om-Doiphode! Thanks for the fix and the test!

**Pull request merged**
